### ISSUE TITLE
problem running plugin

### ISSUE THREAD

**Issue by dmcd** [drone-plugins/drone-tutum#2]
Hi there,

I've not able to run this plugin on drone:0.4. My drone file includes this:

```
deploy:
  tutum:
    username: geoplex
    api_key: $$TUTUM_PASSWORD
    service: osed-client-ad67c0e8
    image: tutum.co/geoplex/osed-client:latest
    redeploy: true
    reuse_volumes: true
```

The build fails right away. Seems to be a problem with the image parameter. I've tried surrounding with quotes.

[DRONE] starting job #1
[info] Plugin tutum.co/geoplex/osed-client:latest is not in the whitelist
[DRONE] finished job #1
[DRONE] exit code 1
[DRONE] job #1 failed
[DRONE] build failed
